<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Employee;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $employees = [

              [
        'employee_id' => 'EMP001',
        'name' => 'Rahul Kumar',
        'email' => 'rahul.kumar@gmail.com',
        'phone' => '9876543210',
        'designation' => 'Flutter Developer',
        'department' => 'IT',
        'location' => 'Chennai',
        'salary' => 75000,
        'blood_group' => 'O+',
        'profile_image' => 'https://i.pravatar.cc/300?img=1',
        'joining_date' => '2018-01-10',
        'employment_type' => 'full_time',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'employee_id' => 'EMP002',
        'name' => 'Priya Sharma',
        'email' => 'priya.sharma@outlook.com',
        'phone' => '9876543211',
        'designation' => 'HR Manager',
        'department' => 'HR',
        'location' => 'Mumbai',
        'salary' => 82000,
        'blood_group' => 'A+',
        'profile_image' => 'https://i.pravatar.cc/300?img=5',
        'joining_date' => '2019-03-15',
        'employment_type' => 'full_time',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'employee_id' => 'EMP003',
        'name' => 'Arjun Mehta',
        'email' => 'arjun.mehta@gmail.com',
        'phone' => '9876543212',
        'designation' => 'Backend Developer',
        'department' => 'IT',
        'location' => 'Bangalore',
        'salary' => 92000,
        'blood_group' => 'B+',
        'profile_image' => 'https://i.pravatar.cc/300?img=12',
        'joining_date' => '2020-06-01',
        'employment_type' => 'full_time',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'employee_id' => 'EMP004',
        'name' => 'Ananya Iyer',
        'email' => 'ananya.iyer@company.com',
        'phone' => '9876543213',
        'designation' => 'UI/UX Designer',
        'department' => 'IT',
        'location' => 'Hyderabad',
        'salary' => 68000,
        'blood_group' => 'AB+',
        'profile_image' => 'https://i.pravatar.cc/300?img=9',
        'joining_date' => '2021-02-20',
        'employment_type' => 'full_time',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'employee_id' => 'EMP005',
        'name' => 'Vikram Singh',
        'email' => 'vikram.singh@gmail.com',
        'phone' => '9876543214',
        'designation' => 'DevOps Engineer',
        'department' => 'IT',
        'location' => 'Pune',
        'salary' => 105000,
        'blood_group' => 'O-',
        'profile_image' => 'https://i.pravatar.cc/300?img=13',
        'joining_date' => '2017-11-05',
        'employment_type' => 'full_time',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'employee_id' => 'EMP006',
        'name' => 'Kavita Reddy',
        'email' => 'kavita.reddy@outlook.com',
        'phone' => '9876543215',
        'designation' => 'Finance Analyst',
        'department' => 'Finance',
        'location' => 'Delhi',
        'salary' => 71000,
        'blood_group' => 'A-',
        'profile_image' => 'https://i.pravatar.cc/300?img=16',
        'joining_date' => '2019-08-12',
        'employment_type' => 'full_time',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'employee_id' => 'EMP007',
        'name' => 'Rohan Desai',
        'email' => 'rohan.desai@gmail.com',
        'phone' => '9876543216',
        'designation' => 'Marketing Executive',
        'department' => 'Marketing',
        'location' => 'Mumbai',
        'salary' => 55000,
        'blood_group' => 'B-',
        'profile_image' => 'https://i.pravatar.cc/300?img=14',
        'joining_date' => '2022-01-18',
        'employment_type' => 'full_time',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'employee_id' => 'EMP008',
        'name' => 'Neha Kapoor',
        'email' => 'neha.kapoor@company.com',
        'phone' => '9876543217',
        'designation' => 'Recruitment Specialist',
        'department' => 'HR',
        'location' => 'Gurgaon',
        'salary' => 62000,
        'blood_group' => 'O+',
        'profile_image' => 'https://i.pravatar.cc/300?img=10',
        'joining_date' => '2020-09-01',
        'employment_type' => 'full_time',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'employee_id' => 'EMP009',
        'name' => 'Suresh Nair',
        'email' => 'suresh.nair@gmail.com',
        'phone' => '9876543218',
        'designation' => 'Operations Manager',
        'department' => 'Operations',
        'location' => 'Kochi',
        'salary' => 95000,
        'blood_group' => 'AB-',
        'profile_image' => 'https://i.pravatar.cc/300?img=15',
        'joining_date' => '2016-04-22',
        'employment_type' => 'full_time',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'employee_id' => 'EMP010',
        'name' => 'Divya Menon',
        'email' => 'divya.menon@outlook.com',
        'phone' => '9876543219',
        'designation' => 'QA Engineer',
        'department' => 'IT',
        'location' => 'Chennai',
        'salary' => 64000,
        'blood_group' => 'A+',
        'profile_image' => 'https://i.pravatar.cc/300?img=20',
        'joining_date' => '2021-07-14',
        'employment_type' => 'contract',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'employee_id' => 'EMP011',
        'name' => 'Karthik Rao',
        'email' => 'karthik.rao@gmail.com',
        'phone' => '9876543220',
        'designation' => 'Data Analyst',
        'department' => 'IT',
        'location' => 'Bangalore',
        'salary' => 78000,
        'blood_group' => 'B+',
        'profile_image' => 'https://i.pravatar.cc/300?img=11',
        'joining_date' => '2019-12-02',
        'employment_type' => 'full_time',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'employee_id' => 'EMP012',
        'name' => 'Meera Joshi',
        'email' => 'meera.joshi@company.com',
        'phone' => '9876543221',
        'designation' => 'Accountant',
        'department' => 'Finance',
        'location' => 'Ahmedabad',
        'salary' => 58000,
        'blood_group' => 'O+',
        'profile_image' => 'https://i.pravatar.cc/300?img=24',
        'joining_date' => '2022-05-09',
        'employment_type' => 'full_time',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'employee_id' => 'EMP013',
        'name' => 'Aditya Verma',
        'email' => 'aditya.verma@gmail.com',
        'phone' => '9876543222',
        'designation' => 'Product Manager',
        'department' => 'IT',
        'location' => 'Bangalore',
        'salary' => 118000,
        'blood_group' => 'A+',
        'profile_image' => 'https://i.pravatar.cc/300?img=3',
        'joining_date' => '2018-09-17',
        'employment_type' => 'full_time',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'employee_id' => 'EMP014',
        'name' => 'Sneha Patil',
        'email' => 'sneha.patil@outlook.com',
        'phone' => '9876543223',
        'designation' => 'Content Writer',
        'department' => 'Marketing',
        'location' => 'Pune',
        'salary' => 48000,
        'blood_group' => 'B+',
        'profile_image' => 'https://i.pravatar.cc/300?img=26',
        'joining_date' => '2023-03-06',
        'employment_type' => 'part_time',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'employee_id' => 'EMP015',
        'name' => 'Manoj Pillai',
        'email' => 'manoj.pillai@gmail.com',
        'phone' => '9876543224',
        'designation' => 'System Administrator',
        'department' => 'IT',
        'location' => 'Chennai',
        'salary' => 72000,
        'blood_group' => 'O-',
        'profile_image' => 'https://i.pravatar.cc/300?img=17',
        'joining_date' => '2017-02-28',
        'employment_type' => 'full_time',
        'status' => 'inactive',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'employee_id' => 'EMP016',
        'name' => 'Ishita Banerjee',
        'email' => 'ishita.banerjee@company.com',
        'phone' => '9876543225',
        'designation' => 'Business Analyst',
        'department' => 'Operations',
        'location' => 'Kolkata',
        'salary' => 85000,
        'blood_group' => 'AB+',
        'profile_image' => 'https://i.pravatar.cc/300?img=32',
        'joining_date' => '2020-04-11',
        'employment_type' => 'full_time',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'employee_id' => 'EMP017',
        'name' => 'Nikhil Agarwal',
        'email' => 'nikhil.agarwal@gmail.com',
        'phone' => '9876543226',
        'designation' => 'Sales Lead',
        'department' => 'Marketing',
        'location' => 'Jaipur',
        'salary' => 88000,
        'blood_group' => 'A-',
        'profile_image' => 'https://i.pravatar.cc/300?img=18',
        'joining_date' => '2019-01-07',
        'employment_type' => 'full_time',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'employee_id' => 'EMP018',
        'name' => 'Pooja Krishnan',
        'email' => 'pooja.krishnan@outlook.com',
        'phone' => '9876543227',
        'designation' => 'Payroll Executive',
        'department' => 'HR',
        'location' => 'Chennai',
        'salary' => 52000,
        'blood_group' => 'O+',
        'profile_image' => 'https://i.pravatar.cc/300?img=45',
        'joining_date' => '2022-10-24',
        'employment_type' => 'full_time',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'employee_id' => 'EMP019',
        'name' => 'Harsh Malhotra',
        'email' => 'harsh.malhotra@gmail.com',
        'phone' => '9876543228',
        'designation' => 'Security Engineer',
        'department' => 'IT',
        'location' => 'Delhi',
        'salary' => 99000,
        'blood_group' => 'B+',
        'profile_image' => 'https://i.pravatar.cc/300?img=33',
        'joining_date' => '2021-11-30',
        'employment_type' => 'full_time',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'employee_id' => 'EMP020',
        'name' => 'Ritu Saxena',
        'email' => 'ritu.saxena@company.com',
        'phone' => '9876543229',
        'designation' => 'Legal Advisor',
        'department' => 'Operations',
        'location' => 'Noida',
        'salary' => 110000,
        'blood_group' => 'A+',
        'profile_image' => 'https://i.pravatar.cc/300?img=47',
        'joining_date' => '2015-08-19',
        'employment_type' => 'contract',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'employee_id' => 'EMP021',
        'name' => 'Sanjay Thakur',
        'email' => 'sanjay.thakur@gmail.com',
        'phone' => '9876543230',
        'designation' => 'Warehouse Supervisor',
        'department' => 'Operations',
        'location' => 'Indore',
        'salary' => 46000,
        'blood_group' => 'O+',
        'profile_image' => 'https://i.pravatar.cc/300?img=52',
        'joining_date' => '2018-05-03',
        'employment_type' => 'full_time',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'employee_id' => 'EMP022',
        'name' => 'Lakshmi Subramanian',
        'email' => 'lakshmi.subramanian@outlook.com',
        'phone' => '9876543231',
        'designation' => 'Scrum Master',
        'department' => 'IT',
        'location' => 'Coimbatore',
        'salary' => 102000,
        'blood_group' => 'B-',
        'profile_image' => 'https://i.pravatar.cc/300?img=44',
        'joining_date' => '2019-07-22',
        'employment_type' => 'full_time',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'employee_id' => 'EMP023',
        'name' => 'Farhan Ali',
        'email' => 'farhan.ali@gmail.com',
        'phone' => '9876543232',
        'designation' => 'Mobile Developer',
        'department' => 'IT',
        'location' => 'Hyderabad',
        'salary' => 80000,
        'blood_group' => 'AB+',
        'profile_image' => 'https://i.pravatar.cc/300?img=60',
        'joining_date' => '2023-01-16',
        'employment_type' => 'full_time',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'employee_id' => 'EMP024',
        'name' => 'Tanvi Bhatia',
        'email' => 'tanvi.bhatia@company.com',
        'phone' => '9876543233',
        'designation' => 'Graphic Designer',
        'department' => 'Marketing',
        'location' => 'Chandigarh',
        'salary' => 56000,
        'blood_group' => 'A+',
        'profile_image' => 'https://i.pravatar.cc/300?img=38',
        'joining_date' => '2022-08-01',
        'employment_type' => 'part_time',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'employee_id' => 'EMP025',
        'name' => 'Gaurav Choudhary',
        'email' => 'gaurav.choudhary@gmail.com',
        'phone' => '9876543234',
        'designation' => 'CTO Office Coordinator',
        'department' => 'IT',
        'location' => 'Bangalore',
        'salary' => 67000,
        'blood_group' => 'O+',
        'profile_image' => 'https://i.pravatar.cc/300?img=68',
        'joining_date' => '2024-02-12',
        'employment_type' => 'full_time',
        'status' => 'active',
        'created_at' => now(),
        'updated_at' => now(),
    ],
        ];

        $now = now();
        $rows = collect($employees)->map(function (array $row, int $index) use ($now) {
            if (($row['employment_type'] ?? '') === 'contract') {
                $row['employment_type'] = 'part_time';
            }

            return array_merge(
                [
                    'gender' => $index % 2 === 0 ? 'male' : 'female',
                    'dob' => sprintf('1990-%02d-15', ($index % 12) + 1),
                    'address' => sprintf('%d Sample Street, India', $index + 1),
                    'emergency_contact' => sprintf('98765%05d', $index),
                ],
                $row,
                [
                    'created_at' => $now,
                    'updated_at' => $now,
                ]
            );
        })->all();

        Employee::query()->delete();
        Employee::insert($rows);
    }
}